server:
  port:8089
  error:
    include-message:ALWAYS
spring:
  cloud:
    config:
      enabled:false
  jpa:
    database:POSTGRESQL
  hibernate:
    ddl-auto:update
  datasource:
    driver-class-name:org.postgresql.Driver
    url:jdbc:postgresql://localhost:5432/product
    username:postgres
    password:educ77 
